apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-counter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aaronnbrock/3-tier-counter-infra.git        #if you are using same gitrepo then ArgoCD Rollout must be installed!
    targetRevision: HEAD
    path: deployment/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
