apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-secrets.yaml
- backend.yaml
- frontend.yaml


images:
- name: gcr.io/sada-aaron-brock/3-tier-counter-backend:latest
  newName: gcr.io/sada-aaron-brock/3-tier-counter-backend
  newTag: latest
- name: gcr.io/sada-aaron-brock/3-tier-counter-frontend:latest
  newName: gcr.io/sada-aaron-brock/3-tier-counter-frontend
  newTag: latest
